### ISSUE TITLE
[PE-D][Tester E] Issue with find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#141]
I can use 'find' command because it is listed in the help window but not found in User Guide

![Screenshot 2023-11-03 164904.png](https://raw.githubusercontent.com/teozhengyang/ped/main/files/4d30af0e-d8dd-4c97-87b8-bd62b6eea6f1.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: teozhengyang/ped#3

**Comment by StevenLiudw** [comment]
This is fixed by the userguide so this is a bug instead of featureflaw
