### ISSUE TITLE
[PE-D][Tester A] User guide command format misleading for deleting teams.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#149]
The command format for the deleting teams is: 

![Screenshot 2023-11-03 at 16.28.19.png](https://raw.githubusercontent.com/aliciamichellew/ped/main/files/24e6c46f-dae2-46e8-bf2b-7ab5a57a53aa.png)

However, when I try it:

![Screenshot 2023-11-03 at 16.28.36.png](https://raw.githubusercontent.com/aliciamichellew/ped/main/files/4bac1020-ee4b-4884-9ad9-585dd51e8649.png)

I believe the command should be `deleteteam` instead

Also, when I see the UG, I can't really understand how the command works and how I should delete teams. Maybe you can consider writing more in your UG and provide meaningful examples.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: aliciamichellew/ped#6

**Comment by adhigop13** [comment]
Duplicate issue. This documentation bug has now been resolved.
