### ISSUE TITLE
[PE-D][Tester D] listing teams works even with additional arguments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#152]
listing teams using the "listt" command works even with additional arguments after the word "listt", e.g. "listt aagaqgiqgqg"

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nikele2001/ped#5

**Comment by StevenLiudw** [comment]
This should be fine, but need to add notes in the UG to explain the expected outputs.
