### ISSUE TITLE
[PE-D][Tester E] Commands standardisation issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#154]
Edit team command is under the same section as edit developer command but add and delete team and developer commands are in different sections. Should standardise how the UG is written

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: teozhengyang/ped#6

**Comment by adhigop13** [comment]
Standardisation has now been done. Thanks for pointing this out.
