### ISSUE TITLE
[PE-D][Tester E] Add command example is wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#168]
The example given for the add command shows tag under remarks 
![Screenshot 2023-11-03 165118.png](https://raw.githubusercontent.com/teozhengyang/ped/main/files/d4919f0c-4f38-4c71-b173-8800da188e79.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: teozhengyang/ped#9

**Comment by adhigop13** [comment]
We replicated the same scenario, but were unable to observe this bug. Perhaps the tester did not apply "Space" between the remark and tag parameters. Hence the tag parameter was incorrectly assigned as part of the remark.
