### ISSUE TITLE
[PE-D][Tester B] Uninformative command output when changing views 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-4/tp#171]
When changing UI views with `list`, `listt` or `tree` commands, the output message is the same both when going to those views and returning to the home view. I think it might be better to have a message like "Switched back to default view" when toggling back just to give users better feedback.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: alvinlim277/ped#9

**Comment by adhigop13** [comment]
Thanks for the suggestion. However, this is in line with our design ideas and hence isn't really a feature flaw.
