### ISSUE TITLE
[PE-D][Tester B] Inconvenient to toggle UI views

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W11-4/tp#172]
It seems quite counterintuitive to have to reenter the same specific command matching whatever UI view is being displayed on the screen to toggle back to the default view. It  be better to have a `home` command to just toggle back the view instead.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: alvinlim277/ped#10

**Comment by adhigop13** [comment]
Not really relevant to the testing process. Cannot be considered a bug.
