### ISSUE TITLE
[PE-D][Tester C] Inconsistency in UG formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W11-4/tp#179]
The "Example Usage" header in the UG is not consistent. It would be good to make it consistent.

![Example Usage 1.png](https://raw.githubusercontent.com/geraldngjx/ped/main/files/b6855e09-90d9-4500-840d-592c41be7dfd.png)

![Example Usage 2.png](https://raw.githubusercontent.com/geraldngjx/ped/main/files/3a346186-df9c-4da8-9dd2-559206465ee0.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: geraldngjx/ped#11

**Comment by adhigop13** [comment]
This has now been resolved. Thanks
